[pytest]
testpaths = unit integration e2e
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --strict-markers
    --tb=short
markers =
    slow: медленные тесты
    integration: интеграционные тесты
    unit: юнит тесты
    e2e: end-to-end тесты
